// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cppQuest.Server.Models;

#nullable disable

namespace cppQuest.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403130257_AddIsAdminToUser")]
    partial class AddIsAdminToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("cppQuest.Server.Models.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CoinsEarned")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParagraphId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeSpent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("XpEarned")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("cppQuest.Server.Models.AllowedIsu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IsuNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AllowedIsus");
                });

            modelBuilder.Entity("cppQuest.Server.Models.GamificationProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Coins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FreezeCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Keys")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastActivityDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxStreak")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SnowflakeCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalScrollPixels")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalStreakDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnlockedContentStds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnlockedSlots")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Xp")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("GamificationProfiles");
                });

            modelBuilder.Entity("cppQuest.Server.Models.PageFeedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PageFeedbacks");
                });

            modelBuilder.Entity("cppQuest.Server.Models.ParagraphReadingStats", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParagraphId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CodeRunsCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastReadAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ReadingSessionsCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ScrollPixels")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SrEaseFactor")
                        .HasColumnType("REAL");

                    b.Property<int>("SrInterval")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SrNextDue")
                        .HasColumnType("TEXT");

                    b.Property<int>("SrRepetitions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalReadingSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "ParagraphId");

                    b.ToTable("ParagraphReadingStats");
                });

            modelBuilder.Entity("cppQuest.Server.Models.ParagraphSlotPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostCoins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostKeys")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Std")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Page", "Slot", "Std")
                        .IsUnique();

                    b.ToTable("ParagraphSlotPurchases");
                });

            modelBuilder.Entity("cppQuest.Server.Models.ParagraphTestStats", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AttemptsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BestScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BestStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("LastScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ParagraphId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TestTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalScoreSum")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "TestId");

                    b.ToTable("ParagraphTestStats");
                });

            modelBuilder.Entity("cppQuest.Server.Models.QuestionProgress", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestId")
                        .HasColumnType("TEXT");

                    b.Property<int>("QuestionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectStreak")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextDueAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParagraphId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SrInterval")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "TestId", "QuestionId");

                    b.HasIndex("UserId", "NextDueAt");

                    b.HasIndex("UserId", "TestId");

                    b.ToTable("QuestionProgress");
                });

            modelBuilder.Entity("cppQuest.Server.Models.ShopItem", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CostCoins")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CostKeys")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequiredStd")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ShopItems");

                    b.HasData(
                        new
                        {
                            Id = "std_cpp11",
                            CostCoins = 500,
                            CostKeys = 0,
                            Description = "Лямбды, `auto`, `nullptr`, `range-for`, `std::thread`, move-семантика",
                            Emoji = "⚡",
                            ItemType = "std_unlock",
                            Name = "C++11",
                            RequiredLevel = 2
                        },
                        new
                        {
                            Id = "std_cpp14",
                            CostCoins = 20000,
                            CostKeys = 0,
                            Description = "`auto` в лямбдах, бинарные литералы, relaxed `constexpr`",
                            Emoji = "💧",
                            ItemType = "std_unlock",
                            Name = "C++14",
                            RequiredLevel = 7
                        },
                        new
                        {
                            Id = "std_cpp17",
                            CostCoins = 40000,
                            CostKeys = 0,
                            Description = "`if constexpr`, structured bindings, `std::optional`, `std::variant`",
                            Emoji = "🌪️",
                            ItemType = "std_unlock",
                            Name = "C++17",
                            RequiredLevel = 14
                        },
                        new
                        {
                            Id = "std_cpp20",
                            CostCoins = 80000,
                            CostKeys = 0,
                            Description = "Concepts, Ranges, Coroutines, `std::format`",
                            Emoji = "🔥",
                            ItemType = "std_unlock",
                            Name = "C++20",
                            RequiredLevel = 21
                        },
                        new
                        {
                            Id = "std_cpp23",
                            CostCoins = 100000,
                            CostKeys = 0,
                            Description = "`std::print`, `std::expected`, deducing this, `flat_map`",
                            Emoji = "🌿",
                            ItemType = "std_unlock",
                            Name = "C++23",
                            RequiredLevel = 28
                        });
                });

            modelBuilder.Entity("cppQuest.Server.Models.TestAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CorrectAnswers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectQuestionIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParagraphId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TimeSpent")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WrongQuestionIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TestId");

                    b.ToTable("TestAttempts");
                });

            modelBuilder.Entity("cppQuest.Server.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IsuNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("cppQuest.Server.Models.UserAchievement", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AchievementId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UnlockedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "AchievementId");

                    b.ToTable("UserAchievements");
                });

            modelBuilder.Entity("cppQuest.Server.Models.UserPurchase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId", "ItemId")
                        .IsUnique();

                    b.ToTable("UserPurchases");
                });

            modelBuilder.Entity("cppQuest.Server.Models.ActivityLog", b =>
                {
                    b.HasOne("cppQuest.Server.Models.User", "User")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("cppQuest.Server.Models.GamificationProfile", b =>
                {
                    b.HasOne("cppQuest.Server.Models.User", "User")
                        .WithOne("GamificationProfile")
                        .HasForeignKey("cppQuest.Server.Models.GamificationProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("cppQuest.Server.Models.PageFeedback", b =>
                {
                    b.HasOne("cppQuest.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("cppQuest.Server.Models.ParagraphReadingStats", b =>
                {
                    b.HasOne("cppQuest.Server.Models.User", "User")
                        .WithMany("ReadingStats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("cppQuest.Server.Models.ParagraphSlotPurchase", b =>
                {
                    b.HasOne("cppQuest.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("cppQuest.Server.Models.ParagraphTestStats", b =>
                {
                    b.HasOne("cppQuest.Server.Models.User", "User")
                        .WithMany("TestStats")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("cppQuest.Server.Models.QuestionProgress", b =>
                {
                    b.HasOne("cppQuest.Server.Models.User", "User")
                        .WithMany("QuestionProgress")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("cppQuest.Server.Models.TestAttempt", b =>
                {
                    b.HasOne("cppQuest.Server.Models.User", "User")
                        .WithMany("TestAttempts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("cppQuest.Server.Models.UserAchievement", b =>
                {
                    b.HasOne("cppQuest.Server.Models.User", "User")
                        .WithMany("Achievements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("cppQuest.Server.Models.UserPurchase", b =>
                {
                    b.HasOne("cppQuest.Server.Models.ShopItem", "Item")
                        .WithMany("Purchases")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cppQuest.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("cppQuest.Server.Models.ShopItem", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("cppQuest.Server.Models.User", b =>
                {
                    b.Navigation("Achievements");

                    b.Navigation("ActivityLogs");

                    b.Navigation("GamificationProfile");

                    b.Navigation("QuestionProgress");

                    b.Navigation("ReadingStats");

                    b.Navigation("TestAttempts");

                    b.Navigation("TestStats");
                });
#pragma warning restore 612, 618
        }
    }
}
